DROP MATERIALIZED VIEW  IF EXISTS "analytics"."clusers";
CREATE MATERIALIZED VIEW "analytics"."clusers" BACKUP NO AS
SELECT
   o.org_connectionname,
   u.userid,
   uo.l_jobtitleid,
   u.user_fullname AS usr_masterusername,
   u.user_activationdate AS usr_active,
   u.user_deactivationdate AS usr_inactive,
   u.user_fullname AS usr_fullname,
   uo.prefhomeview AS usr_prefhomeview,
   uo.preftimezoneoffset AS usr_preftimezoneoffset,
   0:: boolean AS usr_system,
   u.email AS usr_email,
   u.phoneoffice AS usr_phoneoffice,
   u.phonecell AS usr_cellphone,
   uo.phonehospitalext AS usr_casslingext,
   uo.homestate AS usr_state,
   0.0 AS usr_approval,
   uo.isengineer AS usr_engineer,
   u.phonehome AS usr_phonehome,
   u.pager AS usr_pager,
   uo.phonehospitalcell AS usr_phonehospitalcell,
   uo.poapprovallimitrfi AS usr_poaprovlimitinventresource,
   uo.poapprovallimitvsc AS usr_poaprovlimitvsc,
   '' AS usr_homeaddress,
   '' AS usr_homecity,
   '' AS usr_homestate,
   '' AS usr_homezip,
   '' AS usr_homephone,
   0 AS usr_vsccanapprove,
   0.0 AS usr_vscapprovallimit,
   0 AS usr_partsinvcanapprove,
   0.0 AS usr_partsinvapprovallimit,
   uo.poapprovallimitse AS usr_seapprovallimit,
   u.created AS usr_created,
   u.createduserid AS usr_createduserid,
   uo.lastupdated AS usr_lastupdated,
   uo.lastupdateduserid AS usr_lastupdateduserid,
   uo.homefacilityid,
   1 AS usr_usenewselist,
   1 AS usr_musicproduction,
   o.useshippinglabel AS usr_useshippinglabel,
   1 AS usr_salem,
   1 AS usr_salemsystemmanagement,
   uo.defaultmatinvlocationid
FROM
   renovomaster.users u
   JOIN renovomaster.userorgs uo ON u.userid = uo.userid
   JOIN renovomaster.organizations o ON uo.orgid = o.orgid;